import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
  icons: 'https://static.cdninstagram.com/rsrc.php/v4/yI/r/VsNE-OHk_8a.png',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
