import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
  icons: [
    {
      url: 'https://static.cdninstagram.com/rsrc.php/v4/ys/r/aM-g435MtEX.png',
      sizes: '32x32',
      rel: 'icon',
      type: 'image/png',
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
